language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
#deploy:
#  provider: heroku
#  api_key:
#    secure: gFPWFSKR3YvYy/fJkckYFIvb8NsOGJiw/2XlskB0PS0GtMGfd0E6RQbbPmmrr47gs2sXOlGKZl1EtcRuty6CMj+Xw0pqynG3nkSaERsuxI00KXvdWAB6fSRwA81/fVXdeXsmdUsfjBqoNYIKM4u47EHUKeWrayfKpbLnCLHx9na9c51zLg/wUl+Sv5I8rWQvKtKNjDrnPSZ1kbShgt8qaC1z5jO8ffZMoQizIiVCZCgc5c11G69suyufJG7XoYEYH4NY5gN61HBXcryWxcrgrFkFnLkPeKgb7Q7A41Fhi9P6ZCAtaOHv8utyxrreY7nRlzmm/vD+DMGDU4gWoGtsfMx5HDGoTs7Uij1B2b5nJIpOT/zARaNyxrP+QFqxObHSu9O9jwKByUwjGsP0etVBri/fxO7zUWf3s771lbICaOjhdfGqpjMEpIv/SD9xE6mk36IPDrjvh9YlDfBBYieIyg/CEojwOmcZB8Z9jDlVSQjZxX/o0+BsPyxrFgwgvCVIUrDQuHAQEfgPp8e70GvdZRYYa1vIfYJZPLB67Av00tfusFFecPGKuGUPvgjouyXMW/yLZx9xL1S0909QuCUrf2krVhAcThqdM2p8j6PV5X1aH8lzpivISamwhCLwEQ6pnxqkX8XMIPJosQXpEY45CIvZDTdLcGdHqq0MhpG3NvA=
